/**
 * Canvas drawing for the compliance credits tail's end card (P2 §3.4 Q5
 * commit 3) -- the untestable-in-Node half of `exportCredits.ts`'s pure text
 * composition, same split as `captureDraw.ts` vs `captureLayout.ts`. Takes a
 * plain `CanvasRenderingContext2D` (never a specific canvas), so
 * `cesium/frameExport.ts`'s credits-tail loop can target its own offscreen
 * canvas exactly like the main flythrough capture already does.
 */
import type { ExportCredits } from './exportCredits'
import type { CreditsCardLayout } from './creditsLayout'

const CARD_BG = '#0b0c10'
const TITLE_COLOR = '#f8fafc'
const LINE_COLOR = '#d1d5db'
const NOTE_COLOR = '#9ca3af'
const MUSIC_NOTE_COLOR = '#fbbf24'
const FOOTER_COLOR = '#6b7280'

const TITLE_TEXT = '数据来源与署名'
const FOOTER_TEXT = 'Generated by TrailCraft'

function fontSpec(sizePx: number, weight?: 600): string {
  return `${weight ? `${weight} ` : ''}${sizePx}px system-ui, sans-serif`
}

/** Shrinks `text`'s font size (never wraps it -- see `creditsLayout.ts`'s
 * own doc comment on why a single generous max-width already covers every
 * credit line this app actually produces) until it measures within
 * `maxWidthPx`, or gives up after a bounded number of steps rather than
 * looping toward an unreadably small size for some pathological input. */
function fitFontPx(ctx: CanvasRenderingContext2D, text: string, startFontPx: number, maxWidthPx: number, weight?: 600): number {
  let fontPx = startFontPx
  for (let i = 0; i < 12 && fontPx > 4; i++) {
    ctx.font = fontSpec(fontPx, weight)
    if (ctx.measureText(text).width <= maxWidthPx) break
    fontPx *= 0.92
  }
  return fontPx
}

/**
 * Draws one frame of the credits tail: a full-bleed dark card with the data
 * credits `composeExportCredits` produced, vertically centred as one block.
 * Deliberately a no-op-safe function of its inputs only (no randomness/time
 * dependence) -- `frameExport.ts` calls this identically for every frame of
 * the tail, which is exactly what makes those frames compress to almost
 * nothing extra in the H.264 stream.
 */
export function drawCreditsCard(
  ctx: CanvasRenderingContext2D,
  width: number,
  height: number,
  credits: ExportCredits,
  layout: CreditsCardLayout,
): void {
  ctx.save()
  ctx.fillStyle = CARD_BG
  ctx.fillRect(0, 0, width, height)

  ctx.textAlign = 'center'
  ctx.textBaseline = 'alphabetic'

  type Line = { text: string; fontPx: number; color: string; weight?: 600 }
  // Three blocks, each stacked with `blockGapPx` between them (and
  // `lineGapPx` between the lines WITHIN a block) -- title on its own, the
  // actual data credits (plus the honest flat-terrain note, if any)
  // together, and the music/footer notes together. Grouping this way (kept
  // separate from the fitting/measuring/drawing pass below) is what makes
  // the vertical centring math and the actual draw loop impossible to drift
  // apart: both walk the exact same nested array.
  const blocks: Line[][] = [
    [{ text: TITLE_TEXT, fontPx: layout.titleFontPx, color: TITLE_COLOR, weight: 600 }],
    [
      ...credits.dataCredits.map((text): Line => ({ text, fontPx: layout.lineFontPx, color: LINE_COLOR })),
      ...(credits.terrainFallbackNote ? [{ text: credits.terrainFallbackNote, fontPx: layout.noteFontPx, color: NOTE_COLOR }] : []),
    ],
    [
      { text: credits.musicNote, fontPx: layout.noteFontPx, color: MUSIC_NOTE_COLOR },
      { text: FOOTER_TEXT, fontPx: layout.noteFontPx, color: FOOTER_COLOR },
    ],
  ]

  // Fit each line's font individually (a pathologically long credit string
  // shrinking shouldn't shrink the title too) before measuring the block's
  // total height, so centring accounts for any shrink that happened.
  const resolvedBlocks = blocks.map((block) =>
    block.map((line) => ({ ...line, fontPx: fitFontPx(ctx, line.text, line.fontPx, layout.maxTextWidthPx, line.weight) })),
  )

  const blockHeight = (block: Line[]) => block.reduce((sum, line) => sum + line.fontPx, 0) + layout.lineGapPx * Math.max(0, block.length - 1)
  const totalHeight = resolvedBlocks.reduce((sum, block) => sum + blockHeight(block), 0) + layout.blockGapPx * (resolvedBlocks.length - 1)

  let y = (height - totalHeight) / 2
  const centerX = width / 2

  for (let b = 0; b < resolvedBlocks.length; b++) {
    for (const line of resolvedBlocks[b]) {
      ctx.font = fontSpec(line.fontPx, line.weight)
      ctx.fillStyle = line.color
      y += line.fontPx
      ctx.fillText(line.text, centerX, y)
      y += layout.lineGapPx
    }
    y += layout.blockGapPx - layout.lineGapPx
  }

  ctx.restore()
}
